from pathlib import Path
import unittest

REPO = Path(__file__).resolve().parents[1]


class FamilyListingUiTest(unittest.TestCase):
    def test_family_board_is_admin_only_and_explains_korean_alias_date_code(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        self.assertIn('우리 매물', html)
        self.assertIn('2026년 8월', html)
        self.assertIn('2608', html)
        self.assertIn('내용 정리하기', html)
        self.assertIn('처음 적은 내용도 같이 남아요', html)
        visible_copy = html + page
        self.assertNotIn('Hermes', visible_copy)
        self.assertNotIn('james', visible_copy)
        self.assertNotIn('사장님', visible_copy)
        self.assertIn('id="familyListingForm"', html)
        self.assertIn('id="familyListingsGrid"', html)
        self.assertIn('id="familyListingSearch"', html)
        self.assertIn('dataset.copyStaff', page)
        self.assertIn("user.app_metadata?.role !== 'admin'", page)
        self.assertIn('signOutAdmin', page)
        self.assertIn('onAuthStateChange', page)
        self.assertIn("event === 'SIGNED_OUT'", page)
        self.assertIn('records = []', page)
        clear_sensitive = page.split('function clearSensitiveView()', 1)[1].split('function setDefaultYearMonth()', 1)[0]
        self.assertIn('resetQuickPostInputs();', clear_sensitive)
        self.assertIn('refs.photoTaskForm?.reset();', clear_sensitive)
        self.assertIn('refs.quickPostPanel.hidden = true;', clear_sensitive)
        self.assertIn('refs.photoTaskPanel.hidden = true;', clear_sensitive)
        self.assertIn('cleanupPhotoDialogState();', clear_sensitive)
        self.assertIn('photoTaskOperationId = null;', clear_sensitive)
        self.assertIn("setAttribute('aria-expanded'", page)
        self.assertIn("setAttribute('aria-controls'", page)
        self.assertNotIn('Kakao', page)
        self.assertNotIn('employeeLogin', html)

    def test_family_board_keeps_older_users_actions_large_and_obvious(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        css = (REPO / 'css' / 'family-listings.css').read_text(encoding='utf-8')
        self.assertIn('글과 사진 같이 올리기', html)
        self.assertIn('사진 찍을 곳 적기', html)
        self.assertIn('id="familyQuickPostForm"', html)
        self.assertIn('id="familyPhotoTaskForm"', html)
        self.assertIn('class="family-editor is-collapsed"', html)
        self.assertNotIn('aria-label="사용 순서"', html)
        self.assertIn('min-height: 58px', css)
        self.assertIn('font-size: 19px', css)
        self.assertNotIn('href="intake.html"', html)
        self.assertNotIn('href="dashboard.html"', html)
        self.assertIn('.family-topbar__actions { grid-template-columns: 1fr; }', css)
        self.assertIn('.form-actions .primary-action { order: -1; }', css)

    def test_quick_post_keeps_each_photo_attached_to_one_listing(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        adapter = (REPO / 'js' / 'services' / 'familyListingAdapter.js').read_text(encoding='utf-8')
        image_adapter = (REPO / 'js' / 'services' / 'adminIntakeImageAdapter.js').read_text(encoding='utf-8')
        migration = (REPO / 'supabase' / 'migrations' / '017_family_listing_photo_access.sql').read_text(encoding='utf-8').lower()
        self.assertIn('id="familyQuickPhotos"', html)
        self.assertIn('data-family-photo-input', page)
        self.assertIn('family_listing_id', page)
        self.assertIn('listFamilyListingPhotoBatches', adapter)
        self.assertIn('chunkValues', adapter)
        self.assertIn('createFamilyListing(payload, options = {})', adapter)
        self.assertIn(".eq('id', recordId)", adapter)
        self.assertIn('createFamilyParseDraft(sourceText, recordId = null, options = {})', adapter)
        self.assertIn('listFamilyParseDrafts(recordIds = [])', adapter)
        self.assertIn('appendSourceRetry', page)
        self.assertIn('sourceSaved', page)
        self.assertIn("metadata->>family_listing_id", adapter)
        self.assertIn('createSignedUrls', image_adapter)
        self.assertIn('.download(', image_adapter)
        self.assertIn('createAdminIntakeImageShareFiles', image_adapter)
        self.assertIn('removeAdminIntakeImages', image_adapter)
        self.assertIn('uploadError?.completedPaths', page)
        self.assertIn('isSelectingPhotos', page)
        self.assertIn('if (isQuickSaving || isSelectingPhotos)', page)
        self.assertIn('setPhotoSelectionLocked', page)
        self.assertIn("refs.photoDialog?.addEventListener('cancel'", page)
        self.assertIn("refs.photoDialog?.addEventListener('close'", page)
        self.assertIn('cleanupPhotoDialogState', page)
        self.assertIn('resetQuickPostInputs', page)
        self.assertGreaterEqual(page.count('resetQuickPostInputs();'), 2)
        self.assertNotIn('getPublicUrl', image_adapter)
        self.assertIn("bucket_id = 'admin-intake-images'", migration)
        self.assertIn('public.is_family_listing_member()', migration)
        self.assertIn("m.metadata ->> 'family_listing_id'", migration)
        self.assertIn("m.metadata ->> 'submitted_by'", migration)
        self.assertIn("m.metadata -> 'private_image_paths'", migration)
        self.assertIn('jsonb_array_elements_text', migration)
        self.assertIn('jsonb_typeof', migration)
        self.assertIn('object_path = storage.objects.name', migration)
        self.assertIn('m.id::text = (storage.foldername(name))[2]', migration)
        self.assertNotIn('public = true', migration)

    def test_cards_offer_field_photo_completion_and_kakao_style_share(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        self.assertIn("photoButton.textContent = '사진 추가'", page)
        self.assertIn('record.alias_code', page)
        self.assertIn("shareButton.textContent = '공유하기'", page)
        self.assertIn('window.confirm', page)
        self.assertIn("shareStatus.className = 'listing-card__share-status'", page)
        self.assertIn("photoLink.className = 'listing-card__cover-link'", page)
        self.assertIn("photoLink.target = '_blank'", page)
        self.assertIn("link.target = '_blank'", page)
        self.assertIn('fullTask.length > 240', page)
        self.assertIn('name="text" maxlength="220" rows="4"', html)
        self.assertIn('name="staffTask" maxlength="240"', html)
        self.assertIn("actions.classList.add('listing-card__actions--photo-needed')", page)
        self.assertIn('navigator.share', page)
        self.assertIn("status: 'needs_info'", page)
        self.assertIn('renderRecords();\n  void refreshRecordDecorations', page)
        self.assertIn('decorationGeneration', page)
        self.assertIn('parseRequestGeneration', page)
        self.assertIn('requestGeneration === parseRequestGeneration', page)
        self.assertIn('parseDecorationFingerprint', page)
        self.assertIn('const changed = await loadParseDraftMap', page)
        self.assertIn('if (changed && generation === decorationGeneration) renderRecords();', page)
        self.assertNotIn('await Promise.all([loadPhotoMap(), loadParseDraftMap()])', page)

    def test_private_contact_and_access_notes_are_allowed_but_hidden_on_cards(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        self.assertIn('연락처·출입정보 메모', html)
        self.assertIn('직원방용 복사에는 들어가지 않습니다', html)
        self.assertNotIn('전화번호, 출입 비밀번호, 계좌번호는 여기 적지 마세요', html)
        self.assertIn("document.createElement('details')", page)
        self.assertIn("summary.textContent = '내부 메모 보기'", page)

    def test_family_card_creates_private_ad_draft_without_publication(self):
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        self.assertIn('buildAdvertisingDraftText', page)
        self.assertIn('buildAdminIntakePayload', page)
        self.assertIn('saveAdminIntakeDraft', page)
        self.assertIn("advertise.textContent = '광고 준비'", page)
        self.assertIn("publish_approved", page)
        self.assertNotIn("status: 'published'", page)

    def test_family_board_uses_private_adapter_without_delete_or_public_publish(self):
        adapter = (REPO / 'js' / 'services' / 'familyListingAdapter.js').read_text(encoding='utf-8')
        self.assertIn(".from('family_listing_records')", adapter)
        self.assertIn(".from('family_listing_events')", adapter)
        self.assertIn('.insert(', adapter)
        self.assertIn('.update(', adapter)
        self.assertNotIn('.delete(', adapter)
        self.assertNotIn('property_listings', adapter)
        self.assertNotIn('service_role', adapter.lower())

    def test_migration_denies_anon_and_allows_only_admin_family_accounts(self):
        migration = (REPO / 'supabase' / 'migrations' / '015_family_listing_records.sql').read_text(encoding='utf-8').lower()
        self.assertIn('create table if not exists public.family_listing_records', migration)
        self.assertIn('enable row level security', migration)
        self.assertIn('revoke all privileges on table public.family_listing_records from anon, authenticated, public', migration)
        self.assertIn('grant select, insert, update on table public.family_listing_records to authenticated', migration)
        self.assertNotIn('grant select on table public.family_listing_records to anon', migration)
        self.assertNotIn('grant delete', migration)
        self.assertNotIn('for delete', migration)
        self.assertIn('create table if not exists public.family_listing_members', migration)
        self.assertIn("check (family_role in ('owner', 'spouse', 'daughter'))", migration)
        self.assertIn('unique (family_role)', migration)
        self.assertIn('grant select on table public.family_listing_members to authenticated', migration)
        self.assertNotIn('grant insert, update, delete on table public.family_listing_members', migration)
        self.assertIn('public.is_family_listing_member()', migration)
        self.assertGreaterEqual(migration.count('public.is_family_listing_member()'), 5)
        self.assertIn('insert into public.family_listing_members', migration)
        self.assertIn("raw_app_meta_data ->> 'role' = 'admin'", migration)
        self.assertNotIn("auth.jwt() -> 'app_metadata' ->> 'role' = 'admin'", migration)
        self.assertIn("check (status in ('new', 'needs_info', 'ready', 'advertising', 'inquiry', 'visit', 'contract', 'completed', 'hold', 'closed'))", migration)
        self.assertIn("check (intake_year_month ~ '^\\d{4}-(0[1-9]|1[0-2])$')", migration)
        self.assertIn('create table if not exists public.family_listing_events', migration)
        self.assertIn('grant select on table public.family_listing_events to authenticated', migration)
        self.assertNotIn('grant insert, update, delete on table public.family_listing_events', migration)
        self.assertIn('after insert or update on public.family_listing_records', migration)
        self.assertIn('security definer', migration)

    def test_page_loads_immutable_history_on_demand(self):
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        self.assertIn('listFamilyListingEvents', page)
        self.assertIn('dataset.history', page)
        self.assertIn('변경 이력', page)

    def test_free_text_parse_review_is_non_destructive_and_private(self):
        html = (REPO / 'admin' / 'family-listings.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'family-listings-page.js').read_text(encoding='utf-8')
        adapter = (REPO / 'js' / 'services' / 'familyListingAdapter.js').read_text(encoding='utf-8')
        migration = (REPO / 'supabase' / 'migrations' / '016_family_listing_parse_reviews.sql').read_text(encoding='utf-8').lower()
        self.assertIn('id="familySourceText"', html)
        self.assertIn('id="requestFamilyParse"', html)
        self.assertIn('id="familyParseReview"', html)
        self.assertIn('아래 입력칸에 채우기', html)
        self.assertIn('createFamilyParseDraft', page)
        self.assertIn('listFamilyParseDrafts', page)
        self.assertIn('finalizeFamilyParseReview', page)
        self.assertNotIn('fetch(', page)
        self.assertNotIn('discord', page.lower())
        self.assertIn(".from('family_listing_parse_reviews')", adapter)
        self.assertIn(".rpc('finalize_family_listing_parse_review'", adapter)
        self.assertNotIn('markFamilyParseDraftReviewed', adapter)
        self.assertIn('create table if not exists public.family_listing_parse_reviews', migration)
        self.assertIn("check (parse_status in ('queued', 'processing', 'review_needed', 'reviewed', 'failed'))", migration)
        self.assertIn('claimed_at timestamptz', migration)
        self.assertIn('attempt_count integer', migration)
        self.assertIn('create or replace function public.finalize_family_listing_parse_review', migration)
        self.assertIn('for update', migration)
        self.assertIn('source_text cannot be changed', migration)
        self.assertIn('public.is_family_listing_member()', migration)
        self.assertNotIn('grant select, insert, update on table public.family_listing_parse_reviews to authenticated', migration)
        self.assertIn('grant select, insert on table public.family_listing_parse_reviews to authenticated', migration)
        self.assertNotIn('grant delete', migration)
        self.assertNotIn('for delete', migration)

    def test_existing_admin_surfaces_link_to_family_board(self):
        intake = (REPO / 'admin' / 'intake.html').read_text(encoding='utf-8')
        dashboard = (REPO / 'admin' / 'dashboard.html').read_text(encoding='utf-8')
        self.assertIn('href="family-listings.html"', intake)
        self.assertIn('href="family-listings.html"', dashboard)


if __name__ == '__main__':
    unittest.main()
