from pathlib import Path
import unittest

REPO = Path(__file__).resolve().parents[1]


class AdminIntakeUiTest(unittest.TestCase):
    def test_chat_first_admin_has_two_large_intent_choices_and_no_publish_action(self):
        html = (REPO / 'admin' / 'intake.html').read_text(encoding='utf-8')
        self.assertIn('id="intakeListingBtn"', html)
        self.assertIn('id="intakeReportBtn"', html)
        self.assertIn('id="intakeMessage"', html)
        self.assertIn('id="saveIntakeBtn"', html)
        self.assertNotIn('id="publishIntakeBtn"', html)
        self.assertIn('자동으로 공개되지 않습니다', html)

    def test_chat_first_admin_uses_accessible_mobile_sizing(self):
        css = (REPO / 'css' / 'admin-intake.css').read_text(encoding='utf-8')
        self.assertIn('font-size: 18px', css)
        self.assertIn('min-height: 52px', css)
        self.assertIn('@media (max-width: 720px)', css)
        self.assertIn('[hidden] { display: none !important; }', css)

    def test_dashboard_links_to_chat_first_intake_as_primary_action(self):
        html = (REPO / 'admin' / 'dashboard.html').read_text(encoding='utf-8')
        self.assertIn('href="intake.html"', html)
        self.assertIn('채팅으로 초안 만들기', html)
        source = (REPO / 'js' / 'admin-dashboard.js').read_text(encoding='utf-8')
        self.assertIn("const section = item.getAttribute('data-section');", source)
        self.assertIn('if (!section) return;', source)

    def test_intake_save_path_is_supabase_only_and_draft_only(self):
        page = (REPO / 'js' / 'admin-intake-page.js').read_text(encoding='utf-8')
        adapter = (REPO / 'js' / 'services' / 'adminIntakeAdapter.js').read_text(encoding='utf-8')
        self.assertIn("from './services/adminIntakeAdapter.js'", page)
        self.assertNotIn('saveReport', page)
        self.assertIn("payload.status !== 'draft'", adapter)
        self.assertIn("payload.metadata?.intake_source !== 'admin-chat'", adapter)
        self.assertIn('payload.metadata?.publish_approved !== false', adapter)
        self.assertIn('if (!supabase)', adapter)
        self.assertNotIn('saveReportMock', adapter)

    def test_listing_intake_supports_private_drag_drop_photos(self):
        html = (REPO / 'admin' / 'intake.html').read_text(encoding='utf-8')
        page = (REPO / 'js' / 'admin-intake-page.js').read_text(encoding='utf-8')
        adapter = (REPO / 'js' / 'services' / 'adminIntakeImageAdapter.js').read_text(encoding='utf-8')
        dimensions = (REPO / 'js' / 'adminIntakeImageDimensions.mjs').read_text(encoding='utf-8')
        draft_adapter = (REPO / 'js' / 'services' / 'adminIntakeAdapter.js').read_text(encoding='utf-8')
        migration = (REPO / 'supabase' / 'migrations' / '009_private_admin_intake_images.sql').read_text(encoding='utf-8')
        finalize_migration = (REPO / 'supabase' / 'migrations' / '010_finalize_admin_intake_images.sql').read_text(encoding='utf-8')
        self.assertIn('id="intakeImageDropzone"', html)
        self.assertIn('id="intakeImages"', html)
        self.assertIn('multiple', html)
        self.assertIn('최대 30장', html)
        self.assertIn('60MB·64MP 이하', html)
        self.assertIn('createImageBitmap(file, {', adapter)
        self.assertIn('resizeWidth', adapter)
        self.assertIn('LEGACY_SOURCE_BYTES', adapter)
        self.assertIn('createAdminIntakeThumbnail', adapter)
        self.assertIn('const CONCURRENCY = 1', adapter)
        self.assertIn('MAX_SOURCE_PIXELS = 64_000_000', dimensions)
        self.assertIn('MAX_SOURCE_DIMENSION = 16_384', dimensions)
        self.assertIn('getOrientedDimensions', adapter)
        self.assertIn('let isSubmitting = false', page)
        self.assertIn('if (isSubmitting)', page)
        self.assertIn('setFormControlsDisabled(true)', page)
        snapshot_index = page.index('const submittedValues = Object.fromEntries(new FormData(form).entries())')
        lock_index = page.index('setFormControlsDisabled(true)', snapshot_index)
        self.assertLess(snapshot_index, lock_index)
        self.assertIn('buildAdminIntakePayload(submittedValues', page)
        self.assertIn('submittedValues.type', page)
        self.assertIn('resetBtn.disabled = true', page)
        self.assertIn('remove.disabled = selectingImages || isSubmitting || Boolean', page)
        self.assertIn('if (selectingImages || isSubmitting || pendingDraftContext?.locked) return;', page)
        self.assertIn('createAdminIntakeThumbnail', page)
        self.assertNotIn('URL.createObjectURL(file)', page)
        self.assertIn('id="newListingIntakeBtn"', html)
        self.assertIn('다른 매물 올리기', html)
        self.assertIn("chooseType('listing')", page)
        self.assertIn('uploadAdminIntakeImages', page)
        self.assertIn('finalizeAdminIntakeImages', page)
        self.assertNotIn('cleanupAdminIntakeImages', page)
        self.assertNotIn('existingKeys', page)
        self.assertLess(page.index('const saved = await saveAdminIntakeDraft'), page.index('uploadedPaths = await uploadAdminIntakeImages'))
        self.assertIn('finalizeAdminIntakeImages', draft_adapter)
        self.assertIn("const BUCKET = 'admin-intake-images'", adapter)
        self.assertIn('.from(BUCKET)', adapter)
        self.assertNotIn('getPublicUrl', adapter)
        self.assertIn("'admin-intake-images'", migration)
        self.assertIn('false,', migration.lower())
        self.assertIn('file_size_limit', migration.lower())
        self.assertIn("auth.jwt() -> 'app_metadata' ->> 'role' = 'admin'", migration)
        self.assertIn('finalize_admin_intake_images', finalize_migration)
        self.assertIn('storage.objects', finalize_migration)
        self.assertIn('photo_batch_prefix', finalize_migration)
        self.assertIn('expected_image_count', finalize_migration)
        self.assertIn('auth.uid()', finalize_migration)


if __name__ == '__main__':
    unittest.main()
